name: Simple Test Workflow

# Trigger this action on every push to any branch
on: [push]

jobs:
  test:
    # Specifies the OS to run the job on
    runs-on: ubuntu-latest

    steps:
      # Checks out the repository code
      - name: Check out code
        uses: actions/checkout@v3

      # Run a simple shell command to test
      - name: Run echo command
        run: echo "Hello, GitHub Actions!"

      # Run a Node.js version check (example for a Node project)
      - name: Check Node.js version
        run: node -v

      # Set up Node.js environment for further steps
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify the desired Node.js version

      # Install dependencies (if you have a package.json file)
      - name: Install dependencies
        run: |
          npm install

      # Run tests (assuming you are using npm)
      - name: Run tests
        run: npm test
