name: Simple Test Workflow

on: [push]

jobs:
  # Job 1: Run a basic test and check Node.js version
  test-basic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "Hello, GitHub Actions!"

      - name: Check Node.js version
        run: node -v

  # Job 2: Setup Node.js environment and install dependencies
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

  # Job 3: Run tests, dependent on setup-node job
  run-tests:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test

  # Job 4: Run linting, dependent on setup-node job
  lint:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run linting
        run: npm run lint

  # Job 5: Build project, dependent on setup-node job
  build:
    runs-on: ubuntu-latest
    needs: setup-node
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build project
        run: npm run build

  # Job 6: Post-lint-task-1, dependent on lint job
  post-lint-task-1:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Perform Post-Lint Task 1
        run: echo "Running post-lint-task-1"

  # Job 7: Post-lint-task-2, dependent on lint job
  post-lint-task-2:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Perform Post-Lint Task 2
        run: echo "Running post-lint-task-2"

  # Job 8: Post-lint-task-3, dependent on lint job
  post-lint-task-3:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Perform Post-Lint Task 3
        run: echo "Running post-lint-task-3"

  # Job 9: Dependent job on post-lint-task-2
  dependent-on-post-lint-task-2:
    runs-on: ubuntu-latest
    needs: post-lint-task-2
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Perform task dependent on post-lint-task-2
        run: echo "Running dependent task for post-lint-task-2"

  # Job 10: Dependent on dependent-on-post-lint-task-2
  dependent-on-dependent-on-post-lint-task-2:
    runs-on: ubuntu-latest
    needs: dependent-on-post-lint-task-2
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Perform task dependent on dependent-on-post-lint-task-2
        run: echo "Running dependent task for dependent-on-post-lint-task-2"
