name: Simple Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Install Dependencies
        run: npm install
        
      - name: Run Build
        run: npm run build

  build-dependent:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Environment
        run: echo "Setting up environment for build-dependent tasks"

      - name: Run Tests
        run: npm test

  build-dep:
    needs: 
      - build
      - build-dependent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Execute Additional Tasks
        run: echo "Running tasks dependent on both build and build-dependent jobs"

  release:
    needs:
      - build
      - build-dependent
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Release
        run: echo "Creating release"
