name: Advanced Test Workflow

on: [push]

jobs:
  # Job 1: Set up environment and check the Node.js version
  setup-environment:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run echo command
        run: echo "Setting up the environment for Node.js!"

      - name: Check Node.js version
        run: node -v

  # Job 2: Set up Node.js, install dependencies, and cache node_modules
  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

  # Job 3: Run linting, dependent on setup-node job
  run-lint:
    runs-on: ubuntu-latest
    needs: setup-node  # This job will only run after setup-node completes
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run linting
        run: npm run lint

  # Job 4: Run tests, dependent on run-lint job
  run-tests:
    runs-on: ubuntu-latest
    needs: run-lint  # This job will only run after run-lint completes
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Run tests
        run: npm test

  # Job 5: Build the application, dependent on run-tests job
  build-app:
    runs-on: ubuntu-latest
    needs: run-tests  # This job will only run after run-tests completes
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Build the application
        run: npm run build
